# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-0.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-0.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-0.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Robin/Development/anspypher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Robin/Development/anspypher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-0.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-0.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Robin/Development/anspypher/CMakeFiles /Users/Robin/Development/anspypher/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Robin/Development/anspypher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named anspypher

# Build rule for target.
anspypher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 anspypher
.PHONY : anspypher

# fast build rule for target.
anspypher/fast:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/build
.PHONY : anspypher/fast

#=============================================================================
# Target rules for targets named deploy

# Build rule for target.
deploy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deploy
.PHONY : deploy

# fast build rule for target.
deploy/fast:
	$(MAKE) -f CMakeFiles/deploy.dir/build.make CMakeFiles/deploy.dir/build
.PHONY : deploy/fast

gen/anspypher.o: gen/anspypher.cpp.o
.PHONY : gen/anspypher.o

# target to build an object file
gen/anspypher.cpp.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/gen/anspypher.cpp.o
.PHONY : gen/anspypher.cpp.o

gen/anspypher.i: gen/anspypher.cpp.i
.PHONY : gen/anspypher.i

# target to preprocess a source file
gen/anspypher.cpp.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/gen/anspypher.cpp.i
.PHONY : gen/anspypher.cpp.i

gen/anspypher.s: gen/anspypher.cpp.s
.PHONY : gen/anspypher.s

# target to generate assembly for a file
gen/anspypher.cpp.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/gen/anspypher.cpp.s
.PHONY : gen/anspypher.cpp.s

gen/anspypher.pb.o: gen/anspypher.pb.cc.o
.PHONY : gen/anspypher.pb.o

# target to build an object file
gen/anspypher.pb.cc.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/gen/anspypher.pb.cc.o
.PHONY : gen/anspypher.pb.cc.o

gen/anspypher.pb.i: gen/anspypher.pb.cc.i
.PHONY : gen/anspypher.pb.i

# target to preprocess a source file
gen/anspypher.pb.cc.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/gen/anspypher.pb.cc.i
.PHONY : gen/anspypher.pb.cc.i

gen/anspypher.pb.s: gen/anspypher.pb.cc.s
.PHONY : gen/anspypher.pb.s

# target to generate assembly for a file
gen/anspypher.pb.cc.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/gen/anspypher.pb.cc.s
.PHONY : gen/anspypher.pb.cc.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/main.cpp.s
.PHONY : main.cpp.s

src/haszh.o: src/haszh.cpp.o
.PHONY : src/haszh.o

# target to build an object file
src/haszh.cpp.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/haszh.cpp.o
.PHONY : src/haszh.cpp.o

src/haszh.i: src/haszh.cpp.i
.PHONY : src/haszh.i

# target to preprocess a source file
src/haszh.cpp.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/haszh.cpp.i
.PHONY : src/haszh.cpp.i

src/haszh.s: src/haszh.cpp.s
.PHONY : src/haszh.s

# target to generate assembly for a file
src/haszh.cpp.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/haszh.cpp.s
.PHONY : src/haszh.cpp.s

src/keyword.o: src/keyword.cpp.o
.PHONY : src/keyword.o

# target to build an object file
src/keyword.cpp.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/keyword.cpp.o
.PHONY : src/keyword.cpp.o

src/keyword.i: src/keyword.cpp.i
.PHONY : src/keyword.i

# target to preprocess a source file
src/keyword.cpp.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/keyword.cpp.i
.PHONY : src/keyword.cpp.i

src/keyword.s: src/keyword.cpp.s
.PHONY : src/keyword.s

# target to generate assembly for a file
src/keyword.cpp.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/keyword.cpp.s
.PHONY : src/keyword.cpp.s

src/matcher.o: src/matcher.c.o
.PHONY : src/matcher.o

# target to build an object file
src/matcher.c.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/matcher.c.o
.PHONY : src/matcher.c.o

src/matcher.i: src/matcher.c.i
.PHONY : src/matcher.i

# target to preprocess a source file
src/matcher.c.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/matcher.c.i
.PHONY : src/matcher.c.i

src/matcher.s: src/matcher.c.s
.PHONY : src/matcher.s

# target to generate assembly for a file
src/matcher.c.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/matcher.c.s
.PHONY : src/matcher.c.s

src/table_scanner.o: src/table_scanner.cpp.o
.PHONY : src/table_scanner.o

# target to build an object file
src/table_scanner.cpp.o:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/table_scanner.cpp.o
.PHONY : src/table_scanner.cpp.o

src/table_scanner.i: src/table_scanner.cpp.i
.PHONY : src/table_scanner.i

# target to preprocess a source file
src/table_scanner.cpp.i:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/table_scanner.cpp.i
.PHONY : src/table_scanner.cpp.i

src/table_scanner.s: src/table_scanner.cpp.s
.PHONY : src/table_scanner.s

# target to generate assembly for a file
src/table_scanner.cpp.s:
	$(MAKE) -f CMakeFiles/anspypher.dir/build.make CMakeFiles/anspypher.dir/src/table_scanner.cpp.s
.PHONY : src/table_scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... anspypher"
	@echo "... deploy"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gen/anspypher.o"
	@echo "... gen/anspypher.i"
	@echo "... gen/anspypher.s"
	@echo "... gen/anspypher.pb.o"
	@echo "... gen/anspypher.pb.i"
	@echo "... gen/anspypher.pb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/haszh.o"
	@echo "... src/haszh.i"
	@echo "... src/haszh.s"
	@echo "... src/keyword.o"
	@echo "... src/keyword.i"
	@echo "... src/keyword.s"
	@echo "... src/matcher.o"
	@echo "... src/matcher.i"
	@echo "... src/matcher.s"
	@echo "... src/table_scanner.o"
	@echo "... src/table_scanner.i"
	@echo "... src/table_scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

